/**
 * needs-input-observer - OpenCode plugin (DIA-122): multi-session
 * "needs developer input" ticker + notifications.
 *
 * Maintains .opencode/session/ticker.json - a persistent cross-session state
 * of which opencode sessions are waiting for developer input (question asked,
 * permission asked, orchestrator idle after delegations). Many sessions run in
 * parallel (DIA-085 worktree model), so the ticker names the WAITING SESSION
 * in every notification. ticker.md is a DERIVED VIEW regenerated by
 * scripts/ticker-render.sh - never edited directly.
 *
 * State machine:
 *   ENTER  question.asked / question.v2.asked -> "question"
 *          permission.asked / permission.v2.asked -> "permission"
 *          orchestrator session.idle with delegationsSinceIdle > 0 -> "idle"
 *          (subagent idle NEVER enters)
 *          tool.execute.before wait_for_user -> "question" (belt-and-
 *          suspenders; dedup makes double-entry harmless)
 *   CLEAR  question.replied / question.v2.replied / question.rejected /
 *          question.v2.rejected / permission.replied / permission.v2.replied
 *          chat.message (genuine user messages only - synthetic compaction
 *          auto-continue messages are suppressed via a per-session flag set
 *          by the experimental.compaction.autocontinue hook, with a TTL)
 *          session.status non-idle (agent resumed work)
 *          session.deleted / session.error (error also records the bucket)
 *   ERROR  session.error -> separate "errors" bucket (NOT waiting; never
 *          notified, only listed in the ticker view)
 *
 * Notification channels (DIA-122 Phase-2 disposition, gate research
 * 2026-08-12: freedesktop dbus REQUIRES a daemon, absent on this WSL2 host):
 *   primary  in-TUI toast via ctx.client.tui.showToast()
 *   desktop  powershell.exe WinRT ToastText02 (WSL interop, zero installs)
 * Only on ENTER transitions, globally debounced ~2s. Errors stay silent in
 * notifications.
 *
 * Cross-cutting (mirror delegation-observer.ts):
 *   - fail-soft everywhere: never crash the plugin, never block the event
 *     loop; console.warn (stderr) on failure and continue.
 *   - TUI-safe logging via ctx.client.app.log(); NO raw console.* stdout
 *     writes (res007 - stdout interleaves with the TUI render surface).
 *   - subprocess stdio discarded (["ignore","ignore","ignore"]) so the WinRT
 *     toast can never corrupt the TUI.
 *   - ASCII-only source (DIA-079): no em-dashes / smart quotes anywhere,
 *     including the PowerShell one-liner.
 */
import { spawn } from "node:child_process"
import { randomUUID } from "node:crypto"
import {
  appendFileSync,
  closeSync,
  existsSync,
  fsyncSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from "node:fs"
import { basename, join } from "node:path"
import type { Hooks, Plugin } from "@opencode-ai/plugin"
// Shared error helpers consolidated from delegation-observer.ts + this file
// (DIA-260825-oyh). Explicit .ts extension: plugins load via
// node --experimental-strip-types as individual files (no bundler).
import { errorMessage } from "./lib/errors.ts"

// ---------------------------------------------------------------------------
// DIA-189 word-pair naming: deterministically maps a session_id to a
// human-readable adjective-noun pair like "bold-fox" or "calm-river".
// Replaces the old 6-char hex short-id suffix for terminal titles.
// ---------------------------------------------------------------------------

// 100 unique adjectives. ADJECTIVES and NOUNS are disjoint sets to prevent
// same-word pairs like "oak-oak". No duplicates (deduped 2026-08-19).
const ADJECTIVES = [
  "bold", "calm", "deep", "fair", "glad", "keen", "mild", "neat", "pure", "rare",
  "safe", "warm", "wise", "brave", "clear", "quiet", "stern", "proud", "crisp", "dark",
  "eager", "fresh", "grave", "hasty", "light", "lucid", "noble", "quick", "sharp", "solid",
  "stark", "tidy", "vivid", "young", "azure", "ivory", "palm", "sage", "fern", "moss",
  "iron", "steel", "scarlet", "golden", "violet", "crimson", "gentle", "fierce", "hollow", "lofty",
  "modest", "placid", "resolute", "serene", "subtle", "valiant", "wistful", "zealous", "ardent", "blithe",
  "canny", "droll", "felicitous", "gregarious", "hearty", "jovial", "luminous", "mirthful", "piquant", "quaint",
  "robust", "sagacious", "tender", "urbane", "venerable", "whimsical", "copper", "silver", "bronze", "stoic",
  "meek", "earnest", "loyal", "arcane", "hidden", "silent", "ancient", "prim", "dire", "fond",
  "ripe", "nimble", "stout", "polite", "radiant", "candid", "ample", "vast", "merry", "plump",
]

const NOUNS = [
  "fox", "hawk", "wolf", "bear", "lynx", "raven", "crane", "swift", "wren", "robin",
  "stag", "hare", "elk", "orca", "finch", "marten", "otter", "badger", "falcon", "osprey",
  "river", "stream", "brook", "lake", "marsh", "spring", "fjord", "creek", "delta", "cove",
  "ridge", "peak", "vale", "glen", "mesa", "cliff", "bluff", "tor", "dale", "moor",
  "oak", "pine", "elm", "ash", "yew", "birch", "cedar", "willow", "maple", "hawthorn",
  "stone", "flint", "quartz", "amber", "pearl", "coral", "jade", "slate", "granite", "obsidian",
  "crown", "forge", "anvil", "lance", "shield", "beacon", "harbor", "bridge", "tower", "gate",
  "flame", "spark", "ember", "mist", "frost", "gale", "storm", "rain", "dew", "fog",
  "star", "moon", "sun", "comet", "nova", "nebula", "aurora", "eclipse", "zenith", "horizon",
  "echo", "whisper", "melody", "rhythm", "harmony", "cadence", "chorus", "requiem", "anthem", "prelude",
]

/**
 * DIA-189: deterministic word-pair from a session_id. FNV-1a string hash
 * split into two indices (adjective, noun). ASCII-only output, no special
 * chars. Same input always produces the same word-pair.
 * FNV-1a chosen over humanhash/moniker/uuid-words to avoid adding
 * dependencies; provides uniform distribution for our scale (10k combinations).
 */
export function sessionWordPair(sessionId: string): string {
  // FNV-1a 32-bit hash - simple, fast, no dependencies.
  let h = 0x811c9dc5
  for (let i = 0; i < sessionId.length; i++) {
    h ^= sessionId.charCodeAt(i)
    h = Math.imul(h, 0x01000193)
  }
  h = h >>> 0 // ensure unsigned
  // Use lower 16 bits for adjective, upper 16 bits for noun to decorrelate
  // indices while keeping hash computation simple.
  const adjIdx = h % ADJECTIVES.length
  const nounIdx = (h >>> 16) % NOUNS.length
  return `${ADJECTIVES[adjIdx]}-${NOUNS[nounIdx]}`
}

type WaitingReason = "question" | "permission" | "idle"

interface WaitingEntry {
  session_id: string
  title?: string
  agent?: string
  reason: WaitingReason
  detail: string
  since: string
}

interface TickerErrorEntry {
  session_id: string
  title?: string
  since: string
  error: string
}

interface TickerDoc {
  version: number
  updated_at: string
  waiting: WaitingEntry[]
  errors: TickerErrorEntry[]
  // DIA-098 R3: pending permission asks (watchdog state). Additive field —
  // the ticker schema stays version 1.
  permissions: PermissionAskRecord[]
}

/**
 * Custom event union for the `event` catch-all hook. The installed
 * @opencode-ai/plugin@1.18.10 v1 TS Event types do NOT declare the
 * question/permission events (and their v2 variants), but the runtime emits
 * them anyway - so we cast via `as` (same approach as the delegation-observer
 * for session lifecycle events).
 */
interface TickerEvent {
  type: string
  properties?: {
    sessionID?: string
    id?: string
    info?: { id?: string; parentID?: string; title?: string; agent?: string }
    questions?: Array<{ question?: string; text?: string; header?: string }>
    permission?: string
    patterns?: string[]
    action?: string
    resources?: string[]
    // DIA-098 R3: reply events reference the asked permission's id — v1
    // permission.replied carries permissionID, v2 permission.v2.replied
    // carries requestID (which equals the asked event's properties.id).
    permissionID?: string
    requestID?: string
    error?: unknown
    status?: unknown
  }
}

/**
 * DIA-098 R3: persisted record of a pending permission ask (ticker.json
 * `permissions` list). The watchdog timer is in-memory; this record survives
 * plugin restarts so a pending permission is re-armed on boot.
 */
interface PermissionAskRecord {
  session_id: string
  permission_id: string
  timestamp: string
  patterns?: string[]
}

/**
 * Synthetic-message guard for the chat.message CLEAR trigger. Compaction
 * auto-continue turns are synthetic user messages that must NOT clear a
 * waiting entry (the session is still waiting - the "continue" is machine-
 * generated). Genuine user messages clear. Variant markers are version-
 * dependent, so match conservatively.
 */
function isSyntheticVariant(variant: string | undefined): boolean {
  if (!variant) return false
  return /synthetic|auto.?continue|compaction/i.test(variant)
}

const NOTIFY_DEBOUNCE_MS = 2000
const DESKTOP_TOAST_DEBOUNCE_MS = 2000
const COMPACTION_SUPPRESS_TTL_MS = 30000

// DIA-260821-3blw: powershell.exe WinRT toast only exists on win32 or WSL
// interop; on pure Linux every spawn is a guaranteed ENOENT warn. The
// platform gate skips silently; a missing binary additionally latches the
// channel off with ONE warn (non-ENOENT failures keep warning per event).
// The latch FLAG itself lives inside the plugin factory (per-instance):
// module-level state would leak an ENOENT latch across plugin instances,
// which the platform-gate suite's fresh-harness guard cases forbid.

/** WSL interop detection (node-notifier / is-wsl idiom). */
function isWSL(): boolean {
  if (process.platform !== "linux") return false
  if (existsSync("/mnt/wslg")) return true
  if (process.env.WSL_DISTRO_NAME) return true
  try {
    return /microsoft/i.test(readFileSync("/proc/version", "utf-8"))
  } catch {
    return false
  }
}

/** Desktop toast channel availability: native Windows or WSL interop. */
function canUsePowershellToast(): boolean {
  return process.platform === "win32" || isWSL()
}

// DIA-260821-5r03: process-scoped singleton guards. Observers load exactly once
// via auto-discovery of .opencode/plugins/; on an in-process plugin reload
// (module re-evaluation without dispose) these globalThis-backed stores survive
// so singleton side-effects (permission timers, title-suffix boot pass, TUI
// toasts, ticker boot-seed) are not re-fired. A full process restart clears
// globalThis, so the side-effects re-run (correct). Symbol-keyed globalThis
// access needs an explicit record view: TS rejects indexing globalThis with a
// runtime Symbol without a declaration, so we retype it (same runtime ref).
const NEEDS_INPUT_PERM_TIMERS_KEY = Symbol.for("needs-input-observer.permissionTimers")
const permTimersStore = globalThis as unknown as Record<symbol, Map<string, ReturnType<typeof setTimeout>> | undefined>
const NEEDS_INPUT_TITLE_BOOT_KEY = Symbol.for("needs-input-observer.titleSuffixBootDone")
const titleBootStore = globalThis as unknown as Record<symbol, boolean | undefined>
const NEEDS_INPUT_TOAST_KEY = Symbol.for("needs-input-observer.notifiedAsks")
const notifiedAsksStore = globalThis as unknown as Record<symbol, Set<string> | undefined>
const NEEDS_INPUT_TICKER_BOOT_KEY = Symbol.for("needs-input-observer.tickerBootSeeded")
const tickerBootStore = globalThis as unknown as Record<symbol, boolean | undefined>

const needsInputObserver: Plugin = async (ctx) => {
  const tickerDir = join(ctx.directory, ".opencode/session")
  const tickerPath = join(tickerDir, "ticker.json")
  const tickerTmpPath = join(tickerDir, ".ticker.json.tmp")

  // sessionID -> lifecycle metadata captured at session.created. Used to
  // distinguish the orchestrator's own session (root, no parentID) from child
  // subagent sessions (role detection for the idle ENTER rule) and to carry
  // human-readable titles/agent names into waiting entries.
  const sessionMeta = new Map<
    string,
    { parentID?: string; role: "orchestrator" | "subagent"; title?: string; agent?: string }
  >()

  // Orchestrator session id, derived at runtime: the session that calls task()
  // IS the orchestrator (same derivation as delegation-observer).
  let parentSessionId: string | undefined

  // Orchestrator session -> number of task() delegations since the last
  // needs-input idle ENTER (mirror of delegation-observer's
  // delegationsSinceHandoff; reset on ENTER so repeated idles without new
  // delegations stay silent).
  const delegationsSinceIdle = new Map<string, number>()

  // sessionID -> timestamp of the last compaction auto-continue. The
  // experimental.compaction.autocontinue hook fires right before a synthetic
  // "continue" user message is added; the following chat.message must not
  // clear the waiting state. TTL-bounded so a never-consumed flag cannot
  // suppress a real user-message clear later.
  const compactionSuppress = new Map<string, number>()

  // In-memory state, seeded from ticker.json on boot (restart/compaction
  // survival). Persisted atomically on every transition.
  const waiting = new Map<string, WaitingEntry>()
  const errors = new Map<string, TickerErrorEntry>()

  // === DIA-098 R3: permission-ask watchdog state ===
  // permissionAsks mirrors the persisted ticker.json `permissions` list;
  // pendingPermissionTimers holds the in-memory setTimeout handles (NOT
  // persisted — they are re-armed from permissionAsks on boot). Key =
  // `${sessionID}:${permissionID}`. ana016 section 6.3 design: ask ->
  // record + registry row + PERMISSION_STALL_TIMEOUT timer; reply -> clear
  // timer + ticker CLEAR; expiry -> auto-reject via the SDK permissions
  // endpoint + registry row + ticker CLEAR(reason) + messages decision row.
  const permissionAsks = new Map<string, PermissionAskRecord>()
  // DIA-260821-5r03 guard 1: the watchdog timer Map lives on globalThis so an
  // in-process reload reuses the SAME handles instead of stacking new ones.
  // armPermissionTimer's has(key) check then dedupes by permission key.
  const pendingPermissionTimers =
    permTimersStore[NEEDS_INPUT_PERM_TIMERS_KEY] ??
    new Map<string, ReturnType<typeof setTimeout>>()
  permTimersStore[NEEDS_INPUT_PERM_TIMERS_KEY] = pendingPermissionTimers
  // DIA-260821-5r03 guard 3: the set of (session_id:reason) already toasted in
  // this process, so a reload does not re-toast a persisted pending ask.
  const notifiedAsks = notifiedAsksStore[NEEDS_INPUT_TOAST_KEY] ?? new Set<string>()
  notifiedAsksStore[NEEDS_INPUT_TOAST_KEY] = notifiedAsks

  // DIA-098 R3: PERMISSION_STALL_TIMEOUT (ana016 section 6.3), env-
  // configurable via PERMISSION_STALL_TIMEOUT_MINUTES, default 5 minutes.
  function permissionTimeoutMs(): number {
    const raw = process.env.PERMISSION_STALL_TIMEOUT_MINUTES
    if (raw) {
      const n = Number.parseInt(raw, 10)
      if (Number.isFinite(n) && n > 0) return n * 60_000
    }
    return 5 * 60_000
  }

  function permissionKey(sessionID: string, permissionID: string): string {
    return `${sessionID}:${permissionID}`
  }

  // Registry + messages paths (DIA-098 R3; ai-auditor finding 1): ana016 gap
  // 1 flagged that the permission watchdog needs registry access. There is
  // no shared utility — delegation-observer owns its appendRow and this
  // plugin owns ticker.json — so the watchdog implements a minimal
  // appendRow-equivalent using the SAME row conventions
  // (seq/timestamp/event/writer for registry.jsonl;
  // row_id/event_uuid/timestamp/gen_ai.provider.name/writer for
  // messages.jsonl). ID allocation is UNIFIED across both plugins: EVERY
  // writer recomputes its id as MAX+1 over the CURRENT file state at write
  // time — no cached in-memory counters exist anywhere. Both plugins run in
  // ONE server process and append synchronously (appendFileSync), so
  // read-compute-append is atomic in the JS thread: no write can interleave
  // between another writer's read and its append, and MAX+1 is therefore
  // provably collision-free under mixed-plugin interleaving (delegation-
  // observer's messages writer additionally floors on the legacy
  // messages.md row numbering — a migration safeguard that only lifts its
  // ids higher and never affects uniqueness, since every write lands in the
  // file before the next read).
  const registryPath = join(ctx.directory, ".opencode/session/registry.jsonl")
  const messagesPath = join(ctx.directory, ".opencode/session/messages.jsonl")

  function maxJsonlNumber(
    filePath: string,
    field: string,
    label: string
  ): number {
    try {
      if (!existsSync(filePath)) return 0
      let max = 0
      for (const line of readFileSync(filePath, "utf-8").split("\n")) {
        if (!line) continue
        try {
          const v = (JSON.parse(line) as Record<string, unknown>)[field]
          if (typeof v === "number" && v > max) max = v
        } catch {
          // Malformed line — skip (same policy as delegation-observer's
          // registry boot scan).
        }
      }
      return max
    } catch (err) {
      console.warn(
        `[needs-input-observer] ${label} scan failed: ${errorMessage(err)}`
      )
      return 0
    }
  }

  /** Registry.jsonl appendRow-equivalent (DIA-098 R3) — same conventions as
   *  delegation-observer's appendRow: seq, timestamp, event, writer. */
  function appendRegistryRow(row: Record<string, unknown>): void {
    try {
      const entry: Record<string, unknown> = {
        seq: maxJsonlNumber(registryPath, "seq", "registry seq") + 1,
        timestamp: new Date().toISOString(),
        ...row,
        writer: "plugin",
      }
      appendFileSync(registryPath, JSON.stringify(entry) + "\n")
    } catch (err) {
      console.warn(
        `[needs-input-observer] registry.jsonl write failed: ${errorMessage(err)}`
      )
    }
  }

  /** Messages.jsonl appendRow-equivalent (DIA-098 R3) — mirrors
   *  delegation-observer's appendMessageRow envelope (row_id, event_uuid,
   *  timestamp, gen_ai.provider.name, writer) for the log_decision row. */
  function appendMessageRow(row: Record<string, unknown>): void {
    try {
      const entry: Record<string, unknown> = {
        row_id: maxJsonlNumber(messagesPath, "row_id", "messages row_id") + 1,
        event_uuid: randomUUID(),
        timestamp: new Date().toISOString(),
        "gen_ai.provider.name": "opencode-go",
        writer: "plugin",
        ...row,
      }
      appendFileSync(messagesPath, JSON.stringify(entry) + "\n")
    } catch (err) {
      console.warn(
        `[needs-input-observer] messages.jsonl write failed: ${errorMessage(err)}`
      )
    }
  }

  /**
   * DIA-098 R3: arm (or re-arm after a plugin restart) the watchdog timer for
   * one pending permission. On expiry the timer calls autoRejectPermission.
   */
  function armPermissionTimer(
    sessionID: string,
    permissionID: string,
    since: string
  ): void {
    const key = permissionKey(sessionID, permissionID)
    if (pendingPermissionTimers.has(key)) return
    const elapsedMs = Date.now() - Date.parse(since)
    // Re-arm with the REMAINING time (a pending permission that survived a
    // plugin restart still auto-rejects on schedule).
    const remainingMs = Math.max(0, permissionTimeoutMs() - elapsedMs)
    const timer = setTimeout(() => {
      void autoRejectPermission(sessionID, permissionID)
    }, remainingMs)
    pendingPermissionTimers.set(key, timer)
  }

  /**
   * DIA-098 R3: ENTER side — record the pending permission (persisted in
   * ticker.json) and arm the 5-minute watchdog timer. Deduped: an already
   * tracked (session, permission) pair is left untouched.
   */
  function startPermissionWatch(
    sessionID: string,
    permissionID: string,
    patterns: string[] | undefined
  ): void {
    const key = permissionKey(sessionID, permissionID)
    if (permissionAsks.has(key)) return
    const record: PermissionAskRecord = {
      session_id: sessionID,
      permission_id: permissionID,
      timestamp: new Date().toISOString(),
      ...(patterns && patterns.length > 0 ? { patterns } : {}),
    }
    permissionAsks.set(key, record)
    persist()
    armPermissionTimer(sessionID, permissionID, record.timestamp)
  }

  /**
   * DIA-098 R3: CLEAR side — stop the timer and drop the persisted record
   * (the ticker "CLEAR transition"). No-op when the pair is untracked.
   */
  function clearPermissionWatch(sessionID: string, permissionID: string): void {
    const key = permissionKey(sessionID, permissionID)
    const timer = pendingPermissionTimers.get(key)
    if (timer !== undefined) {
      clearTimeout(timer)
      pendingPermissionTimers.delete(key)
    }
    if (permissionAsks.delete(key)) persist()
  }

  /** DIA-098 R3: drop every pending permission for a session (session gone). */
  function clearSessionPermissionWatches(sessionID: string): void {
    for (const key of [...permissionAsks.keys()]) {
      const record = permissionAsks.get(key)
      if (record?.session_id === sessionID) {
        clearPermissionWatch(sessionID, record.permission_id)
      }
    }
  }

  /**
   * DIA-098 R3: timer expiry — no human reply within the threshold. Auto-
   * reject via the SDK permission endpoint (ana016 section 6.3), then write
   * the registry audit row, the ticker CLEAR, and the messages log_decision
   * row. The design is FAIL-FAST not auto-resume (ana016 section 6.5): the
   * rejection fails the agent gracefully; the orchestrator re-routes.
   */
  async function autoRejectPermission(
    sessionID: string,
    permissionID: string
  ): Promise<void> {
    const key = permissionKey(sessionID, permissionID)
    const record = permissionAsks.get(key)
    // Guard: a reply that raced the timer removes the record first — never
    // reject an already-resolved permission.
    if (!record) return
    permissionAsks.delete(key)
    pendingPermissionTimers.delete(key)

    const timeoutMs = permissionTimeoutMs()
    const timeoutSeconds = Math.round(timeoutMs / 1000)

    // 1. Auto-reject via the REAL SDK endpoint. ana016 section 6.3 proposed
    //    POST /session/{session_id}/permissions/{permission_id}; the
    //    installed SDK exposes it as postSessionIdPermissionsPermissionId
    //    (URL /session/{id}/permissions/{permissionID}, body {response}).
    //    "reject" is one of the three documented response enum values.
    try {
      const res = await ctx.client.postSessionIdPermissionsPermissionId({
        body: { response: "reject" },
        path: { id: sessionID, permissionID },
      })
      if (res.error) {
        console.warn(
          `[needs-input-observer] permission auto-reject failed for ${sessionID}/${permissionID}: ${errorMessage(res.error)}`
        )
      }
    } catch (err) {
      console.warn(
        `[needs-input-observer] permission auto-reject threw for ${sessionID}/${permissionID}: ${errorMessage(err)}`
      )
    }

    // 2. Registry audit row (ana016 section 6.3 step 2).
    appendRegistryRow({
      event: "permission_auto_rejected",
      session_id: sessionID,
      permission_id: permissionID,
      timeout_seconds: timeoutSeconds,
      reason: "no_human_response_within_threshold",
    })

    // 3. Ticker CLEAR with reason: the persisted record is dropped (the
    //    reason lives in the audit rows above — ticker entries carry no
    //    clear-reason field) and the waiting entry is cleared.
    persist()
    clear(sessionID)

    // 4. messages.jsonl log_decision row — the same semantic contract the
    //    log_decision tool writes (event_type "decision"). content_ref
    //    interpolates the ACTUAL timeout minutes (default 5).
    appendMessageRow({
      "gen_ai.operation.name": "invoke_workflow",
      from: "orchestrator",
      event_type: "decision",
      task_ref: sessionID,
      resolution_status: "escalated",
      content_ref: `permission_auto_rejected_after_${Math.round(timeoutSeconds / 60)}min`,
      next_action: "re-dispatch or fail-fast",
      "gen_ai.agent.id": sessionID,
    })
  }

  // Notification debounce fences (wall-clock, monotonic enough for a ~2s
  // debounce; Date.now() matches delegation-observer conventions).
  let notifyDebounceUntil = 0
  let lastDesktopToastAt = 0

  // DIA-260821-3blw: warn-once latch for the desktop toast channel. Per
  // plugin INSTANCE (not module-level) so a latched instance never leaks
  // into another - the platform-gate suite's fresh-harness guards depend on
  // that isolation.
  let desktopToastDisabled = false

  /**
   * DIA-260821-3blw: ENOENT / "Executable not found" means powershell.exe
   * does not exist on this host - warn ONCE, latch the channel off, and
   * tell the caller to stop (true). Any other failure returns false so the
   * caller keeps its existing per-event warn.
   */
  function disableDesktopToastOnMissingBinary(err: unknown): boolean {
    const msg = errorMessage(err) ?? ""
    const missing =
      (err as { code?: string } | null)?.code === "ENOENT" ||
      /executable not found/i.test(msg)
    if (!missing) return false
    if (!desktopToastDisabled) {
      console.warn(
        "[needs-input-observer] desktop toast disabled (powershell.exe not found)"
      )
      desktopToastDisabled = true
    }
    return true
  }

  /**
   * Generalized atomic JSON write: temp file -> fsync -> atomic rename ->
   * fsync directory (copied from delegation-observer's atomicWriteHandoff).
   * On same-filesystem rename is atomic by POSIX guarantee - a reader sees
   * either the old file or the new file, never a partial write.
   */
  function atomicWriteTicker(content: TickerDoc): void {
    const json = JSON.stringify(content, null, 2) + "\n"
    try {
      writeFileSync(tickerTmpPath, json)
      const tmpFd = openSync(tickerTmpPath, "r+")
      fsyncSync(tmpFd)
      closeSync(tmpFd)
      renameSync(tickerTmpPath, tickerPath)
      const dirFd = openSync(tickerDir, "r")
      fsyncSync(dirFd)
      closeSync(dirFd)
    } catch (err) {
      // Best-effort cleanup: unlink tmp if it still exists (rename failed).
      try {
        if (existsSync(tickerTmpPath)) unlinkSync(tickerTmpPath)
      } catch {
        // Secondary failure - nothing more we can do.
      }
      throw err
    }
  }

  // DIA-260822-unsn: ticker expiry - purge invalid and stale entries during
  // seed/persist. Single shared helper so seed and persist agree. Invalid
  // since (unparseable) always purged; waiting TTL 24h for question/permission
  // and 4h for idle; errors TTL 48h. Future timestamps kept (age < 0).
  const WAITING_TTL_MS: Record<WaitingReason, number> = {
    question: 24 * 3600 * 1000,
    permission: 24 * 3600 * 1000,
    idle: 4 * 3600 * 1000,
  }
  const ERROR_TTL_MS = 48 * 3600 * 1000

  function isExpired(
    entry: { since: string; reason?: WaitingReason },
    nowMs: number
  ): boolean {
    const ts = Date.parse(entry.since)
    if (!Number.isFinite(ts)) return true
    const age = nowMs - ts
    if (age < 0) return false
    if (entry.reason !== undefined) {
      const ttl = WAITING_TTL_MS[entry.reason] ?? WAITING_TTL_MS.question
      return age > ttl
    }
    return age > ERROR_TTL_MS
  }

  function purgeExpired(nowMs = Date.now()): void {
    for (const [id, e] of [...waiting.entries()]) {
      if (isExpired(e, nowMs)) waiting.delete(id)
    }
    for (const [id, e] of [...errors.entries()]) {
      if (isExpired(e, nowMs)) errors.delete(id)
    }
  }

  /**
   * Persist the full ticker state. Fail-soft: never crash the plugin - on
   * write error console.warn (stderr only) and continue. A stale ticker is
   * recoverable; a crashed orchestrator is not.
   */
  function persist(): void {
    try {
      purgeExpired(Date.now())
      mkdirSync(tickerDir, { recursive: true })
      const doc: TickerDoc = {
        version: 1,
        updated_at: new Date().toISOString(),
        waiting: [...waiting.values()].sort((a, b) =>
          a.since.localeCompare(b.since)
        ),
        errors: [...errors.values()].sort((a, b) =>
          a.since.localeCompare(b.since)
        ),
        permissions: [...permissionAsks.values()].sort((a, b) =>
          a.timestamp.localeCompare(b.timestamp)
        ),
      }
      atomicWriteTicker(doc)
    } catch (err) {
      console.warn(
        `[needs-input-observer] ticker.json write failed: ${errorMessage(err)}`
      )
    }
  }

  /**
   * Boot seed: re-read ticker.json so the ticker survives plugin restarts and
   * context compaction. Fail-soft on malformed JSON - start empty.
   */
  function seedFromDisk(): void {
    try {
      if (!existsSync(tickerPath)) return
      const raw = readFileSync(tickerPath, "utf-8")
      const doc = JSON.parse(raw) as Partial<TickerDoc>
      for (const e of Array.isArray(doc.waiting) ? doc.waiting : []) {
        if (e && typeof e.session_id === "string" && typeof e.reason === "string") {
          waiting.set(e.session_id, {
            session_id: e.session_id,
            title: typeof e.title === "string" ? e.title : undefined,
            agent: typeof e.agent === "string" ? e.agent : undefined,
            reason: e.reason as WaitingReason,
            detail: typeof e.detail === "string" ? e.detail : "",
            since: typeof e.since === "string" ? e.since : new Date().toISOString(),
          })
        }
      }
      for (const e of Array.isArray(doc.errors) ? doc.errors : []) {
        if (e && typeof e.session_id === "string") {
          errors.set(e.session_id, {
            session_id: e.session_id,
            title: typeof e.title === "string" ? e.title : undefined,
            since: typeof e.since === "string" ? e.since : new Date().toISOString(),
            error: typeof e.error === "string" ? e.error : "",
          })
        }
      }
      // DIA-098 R3: restore pending permission asks and re-arm their
      // watchdog timers with the REMAINING time. A permission that was
      // already replied while the plugin was down eventually times out and
      // the reject POST fails with a 404 — fail-soft, and the stale
      // CLEAR keeps the ticker honest.
      const permRecords: PermissionAskRecord[] = []
      for (const e of Array.isArray(doc.permissions) ? doc.permissions : []) {
        if (
          !e ||
          typeof e.session_id !== "string" ||
          typeof e.permission_id !== "string"
        ) {
          continue
        }
        const record: PermissionAskRecord = {
          session_id: e.session_id,
          permission_id: e.permission_id,
          timestamp:
            typeof e.timestamp === "string"
              ? e.timestamp
              : new Date().toISOString(),
          ...(Array.isArray(e.patterns) && e.patterns.length > 0
            ? { patterns: e.patterns }
            : {}),
        }
        permissionAsks.set(
          permissionKey(record.session_id, record.permission_id),
          record
        )
        permRecords.push(record)
      }
      // DIA-260822-unsn: purge invalid/stale waiting/error entries so a stale
      // ticker does not survive a restart or a persist round-trip. Shared helper
      // with persist() (single purge path).
      purgeExpired(Date.now())
      // DIA-260821-5r03 guard 4: re-arm watchdog timers at most once per
      // process. The globalThis-backed pendingPermissionTimers Map (guard 1)
      // already dedupes by key, but we also gate the re-arm on the ticker-boot
      // flag so an in-process reload does not re-walk the permission list and
      // double-seed timers. permissionAsks is always re-populated above (it is
      // per-instance and required for correctness across reloads). The flag
      // itself is armed by the factory after seedFromDisk() returns (so it is
      // set even when ticker.json is absent), see the call site.
      if (!tickerBootStore[NEEDS_INPUT_TICKER_BOOT_KEY]) {
        for (const record of permRecords) {
          armPermissionTimer(
            record.session_id,
            record.permission_id,
            record.timestamp
          )
        }
      }
    } catch (err) {
      console.warn(
        `[needs-input-observer] ticker.json boot seed failed, starting empty: ${errorMessage(err)}`
      )
    }
  }

  /** CLEAR transition: remove the session from waiting. No-op when absent. */
  function clear(sessionID: string): void {
    if (!waiting.delete(sessionID)) return
    persist()
  }

  /**
   * ERROR bucket transition (separate from waiting, per spec): record the
   * error; also drop the session from waiting (an errored turn is no longer
   * waiting for input). Errors are NEVER notified - only listed in the ticker
   * view.
   */
  function recordError(sessionID: string, error: string): void {
    waiting.delete(sessionID)
    errors.set(sessionID, {
      session_id: sessionID,
      title: sessionMeta.get(sessionID)?.title,
      since: new Date().toISOString(),
      error,
    })
    persist()
  }

  /**
   * Title fallback for notifications: cached title -> sessionMeta title ->
   * ctx.client.session.get() (fail-soft) -> id. The SDK call is awaited by
   * the caller (notify), so this path never blocks a hook on failure.
   */
  async function resolveTitle(sessionID: string): Promise<string> {
    const cached = sessionMeta.get(sessionID)?.title
    if (cached) return cached
    try {
      const res = await ctx.client.session.get({ path: { id: sessionID } })
      if (!res.error && res.data) {
        const info = res.data as { title?: string }
        if (typeof info.title === "string" && info.title) return info.title
      }
    } catch (err) {
      console.warn(
        `[needs-input-observer] session.get title fallback failed: ${errorMessage(err)}`
      )
    }
    return sessionID
  }

  /**
   * Desktop notification via powershell.exe WinRT toast (WSL interop; the
   * WSLg dbus path was gated out because freedesktop Notifications requires a
   * daemon absent on this host - DIA-122 gate research). One line; printable
   * Unicode preserved (DIA-189 A3 - Cyrillic notification text must survive),
   * control chars stripped, single quotes doubled for PowerShell.
   * STDOUT/STDERR discarded (res007 TUI corruption rule).
   */
  function fireDesktopToast(title: string, body: string): void {
    // DIA-260821-3blw: platform gate (skip silently on pure Linux) then the
    // missing-binary latch (warn-once already emitted; stay silent after).
    if (!canUsePowershellToast()) return
    if (desktopToastDisabled) return
    const now = Date.now()
    if (now - lastDesktopToastAt < DESKTOP_TOAST_DEBOUNCE_MS) return
    lastDesktopToastAt = now
    // DIA-189 A3: printable-Unicode-preserving sanitizer. The old
    // [^\x20-\x7E] strip turned Cyrillic (and every non-ASCII script) into
    // spaces, making Ukrainian notification text invisible in the toast.
    // Only control chars (U+0000-U+001F, U+007F-U+009F) are stripped;
    // CR/LF/TAB collapse first (unchanged), single quotes double for
    // PowerShell (unchanged), and the 180-char truncation stays.
    const sanitize = (s: string): string =>
      s
        .replace(/[\r\n\t]+/g, " ")
        // eslint-disable-next-line no-control-regex -- C0/C1 strip is the A3 intent
        .replace(/[\x00-\x1F\x7F-\x9F]/g, " ")
        .replace(/'/g, "''")
        .slice(0, 180)
    const script =
      "[Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null; " +
      "$t=[Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText02); " +
      `$t.GetElementsByTagName('text').Item(0).AppendChild($t.CreateTextNode('${sanitize(title)}'))|Out-Null; ` +
      `$t.GetElementsByTagName('text').Item(1).AppendChild($t.CreateTextNode('${sanitize(body)}'))|Out-Null; ` +
      "[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('opencode').Show([Windows.UI.Notifications.ToastNotification]::new($t))"
    try {
      const child = spawn("powershell.exe", ["-NoProfile", "-Command", script], {
        stdio: ["ignore", "ignore", "ignore"],
      })
      // Never let a late spawn error (ENOENT, exec failure) become an
      // unhandled 'error' event - the plugin must not crash the session.
      child.on("error", (err) => {
        if (disableDesktopToastOnMissingBinary(err)) return
        console.warn(
          `[needs-input-observer] powershell.exe toast spawn failed: ${errorMessage(err)}`
        )
      })
    } catch (err) {
      if (disableDesktopToastOnMissingBinary(err)) return
      console.warn(
        `[needs-input-observer] powershell.exe toast failed: ${errorMessage(err)}`
      )
    }
  }

  /**
   * Notify on ENTER transitions only (~2s global debounce): in-TUI toast via
   * ctx.client.tui.showToast() (primary channel) + powershell.exe WinRT
   * desktop toast (away-from-terminal channel) + TUI-safe app.log. Fail-soft:
   * if the server client has no tui endpoint the call resolves with an error
   * (ThrowOnError=false) - we just warn and continue.
   */
  async function notify(entry: WaitingEntry): Promise<void> {
    // Every ENTER transition is logged (durable audit trail, TUI-safe). Only
    // the user-facing channels (TUI toast + desktop toast) are debounced.
    ctx.client.app.log({
      body: {
        service: "needs-input-observer",
        level: "info",
        message: `[needs-input-observer] needs-input: ${entry.reason} session=${entry.session_id} title=${entry.title ?? ""}`,
      },
    })

    const now = Date.now()
    if (now < notifyDebounceUntil) return
    notifyDebounceUntil = now + NOTIFY_DEBOUNCE_MS

    // DIA-260821-5r03 guard 3: do not re-toast an ask already notified in this
    // process. On an in-process reload, enter() re-fires for persisted waiting
    // sessions; the globalThis-backed notifiedAsks Set survives the reload so
    // the duplicate toast is suppressed (the audit log above still records it).
    const toastKey = `${entry.session_id}:${entry.reason}`
    if (notifiedAsks.has(toastKey)) return

    const title = entry.title || (await resolveTitle(entry.session_id)) || "Agent needs input"
    // DIA-189 A2: notification attribution. Pin the same " [<word-pair>]"
    // suffix that A1 wrote into the terminal label so a toast names the
    // session that is asking. Flows into BOTH the tui.showToast title and
    // the desktop toast title - do not special-case one channel. Guard:
    // never double-append when the title already carries the suffix.
    // DIA-189: word-pair suffix replaces the old hex short-id.
    const wordPair = sessionWordPair(entry.session_id)
    const attributedTitle = title.startsWith(`[${wordPair}]`)
      ? title
      : `[${wordPair}] ${title}`
    const message = `${entry.reason}: ${entry.detail}`.slice(0, 200)

    // Record before firing so a concurrent/duplicate path cannot double-toast.
    notifiedAsks.add(toastKey)
    try {
      await ctx.client.tui.showToast({
        body: {
          title: attributedTitle,
          message,
          variant: "warning",
          duration: 6000,
        },
      })
    } catch (err) {
      console.warn(
        `[needs-input-observer] tui.showToast failed: ${errorMessage(err)}`
      )
    }

    fireDesktopToast(attributedTitle, message)
  }

  /**
   * ENTER transition: mark the session needs-input (deduped - an already-
   * waiting session is left untouched; the belt-and-suspenders wait_for_user
   * path therefore cannot double-enter), then persist + notify. The idle
   * caller resets its per-session delegation counter after entering.
   */
  async function enter(
    sessionID: string,
    reason: WaitingReason,
    detail: string
  ): Promise<void> {
    if (waiting.has(sessionID)) return
    const meta = sessionMeta.get(sessionID)
    const entry: WaitingEntry = {
      session_id: sessionID,
      title: meta?.title,
      agent: meta?.agent,
      reason,
      detail,
      since: new Date().toISOString(),
    }
    waiting.set(sessionID, entry)
    persist()
    await notify(entry)
  }

  // DIA-189 F3: rename dedupe. Converging event streams (e.g. pty.created
  // followed by pty.updated with the same still-unsuffixed title) can fire a
  // redundant second rename - idempotent but noisy. Track recently-issued
  // (surface, id, derivedTitle) triples per plugin instance (in-memory only,
  // no persistent state) and skip an identical rename within a short TTL.
  // Lazily pruned on access - no timers.
  const recentRenames = new Map<string, number>()
  const RENAME_DEDUPE_TTL_MS = 5000

  /**
   * DIA-189 F3: check-and-record for the rename dedupe. Returns true when an
   * identical (surface, id, derivedTitle) rename was already issued within
   * the TTL window (caller skips it); otherwise records the rename and
   * returns false.
   */
  function isRecentRename(
    surface: "session" | "pty",
    id: string,
    derivedTitle: string
  ): boolean {
    const now = Date.now()
    // Lazy TTL prune: drop expired entries when we touch the map.
    for (const [key, at] of recentRenames) {
      if (now - at > RENAME_DEDUPE_TTL_MS) recentRenames.delete(key)
    }
    const key = `${surface}:${id}:${derivedTitle}`
    if (recentRenames.has(key)) return true
    recentRenames.set(key, now)
    return false
  }

  /**
   * DIA-189 fix: shared rename-if-not-suffixed rule for the two terminal-
   * title surfaces (Session and Pty). A title that does NOT already carry a
   * " [word-pair]" suffix (e.g. "[bold-fox]") is renamed to
   * "<title> [<word-pair>]" so the terminal strip shows a unique per-session
   * label that notification attribution (A2) can pin. The suffix is appended
   * to ANY unsuffixed title - default OR user-set - because the 1.18.18
   * runtime defaults ("New session - <ISO>" for sessions, "Terminal N" /
   * "Terminal <id4>" for ptys) do not share a fixed prefix, and the
   * developer-approved rule survives future default-format changes. Guards:
   * never double-rename a title that already carries the suffix (the ONLY
   * gate); fail-soft - a cosmetic rename must never crash the plugin
   * (console.warn on error, stderr only, mirroring the plugin's fail-soft
   * pattern). `update` is
   * bound to its SDK client so `this` survives the detached call.
   */
  async function renameDefaultTitle(
    id: string,
    rawTitle: string | undefined,
    surface: "session" | "pty"
  ): Promise<void> {
    const createdTitle = typeof rawTitle === "string" ? rawTitle : ""
    // DIA-189 fix: the dedupe guard is the only gate. The old isDefaultLabel
    // check (title === "" || startsWith("opencode ")) never matched the real
    // 1.18.18 defaults ("New session - <ISO>" / "Terminal N"), so the rename
    // silently never ran (0 of 1,742 sessions ever suffixed). Empty title
    // still falls back to the "opencode <cwd>" base before appending.
    const alreadySuffixed = /^\[[a-z]+-[a-z]+\]/.test(createdTitle)
    if (alreadySuffixed) return
    const DEFAULT_SESSION_RE = /^New session - \d{4}-\d{2}-\d{2}T/
    const baseTitle =
      createdTitle !== "" && !DEFAULT_SESSION_RE.test(createdTitle)
        ? createdTitle
        : `opencode ${basename(ctx.directory)}`
    const derivedTitle = `[${sessionWordPair(id)}] ${baseTitle}`
    // DIA-189 F3: skip an identical rename already issued within the TTL
    // (dedupes pty.created + pty.updated converging on the same title).
    if (isRecentRename(surface, id, derivedTitle)) return
    const update =
      surface === "session"
        ? ctx.client.session.update.bind(ctx.client.session)
        : ctx.client.pty.update.bind(ctx.client.pty)
    try {
      const res = await update({ path: { id }, body: { title: derivedTitle } })
      if (res.error) {
        console.warn(
          `[needs-input-observer] ${surface}.update rename returned an error for ${id}: ${errorMessage(res.error)}`
        )
      }
    } catch (err) {
      console.warn(
        `[needs-input-observer] ${surface}.update rename failed for ${id}: ${errorMessage(err)}`
      )
    }
  }

  /**
   * DIA-189b A2b: boot retro pass. Sessions/ptys created BEFORE this plugin
   * loaded never saw the session.created/pty.created rename, so at startup
   * we iterate the existing pty.list() and session.list() and apply the same
   * rename-if-not-suffixed "<title> [<word-pair>]" rule (DIA-189 fix: any
   * unsuffixed title, default OR user-set). Fail-soft at every seam
   * (a list failure warns and skips that surface; an item update failure
   * warns and continues) - a cosmetic boot task must never crash the plugin
   * or block instantiation. Fired as a void call after seedFromDisk(); the
   * promise chain settles in microtasks (the awaited SDK calls resolve
   * immediately), so no long timer is involved.
   */
  async function bootRetroPass(): Promise<void> {
    try {
      const res = await ctx.client.pty.list()
      // DIA-189 F2: the SDK can resolve with a non-throw { error, data:
      // undefined } envelope. Inspect res.error - silently treating it as an
      // empty list hides the failure - so warn and skip this surface (the
      // session surface below still runs). Harness mocks return the raw
      // array directly, so Array.isArray is the shape discriminator.
      if (!Array.isArray(res) && res.error) {
        console.warn(
          `[needs-input-observer] boot retro pass pty.list returned an error: ${errorMessage(res.error)}`
        )
      } else {
        const ptys = (Array.isArray(res) ? res : (res?.data ?? [])) as Array<{
          id?: string
          title?: string
        }>
        for (const pty of ptys) {
          if (!pty || typeof pty.id !== "string" || !pty.id) continue
          await renameDefaultTitle(pty.id, pty.title, "pty")
        }
      }
    } catch (err) {
      console.warn(
        `[needs-input-observer] boot retro pass pty.list failed: ${errorMessage(err)}`
      )
    }
    try {
      const res = await ctx.client.session.list()
      // DIA-189 F2: symmetric { error } envelope inspection for sessions.
      if (!Array.isArray(res) && res.error) {
        console.warn(
          `[needs-input-observer] boot retro pass session.list returned an error: ${errorMessage(res.error)}`
        )
      } else {
        const sessions = (Array.isArray(res) ? res : (res?.data ?? [])) as Array<{
          id?: string
          title?: string
        }>
        for (const session of sessions) {
          if (!session || typeof session.id !== "string" || !session.id) continue
          await renameDefaultTitle(session.id, session.title, "session")
        }
      }
    } catch (err) {
      console.warn(
        `[needs-input-observer] boot retro pass session.list failed: ${errorMessage(err)}`
      )
    }
  }

  seedFromDisk()

  // DIA-260821-5r03 guard 4: mark the ticker as boot-seeded this process so an
  // in-process reload does not re-walk the permission list / double-seed
  // timers. Set here (not inside seedFromDisk) so it is armed even when
  // ticker.json is absent on a fresh directory.
  tickerBootStore[NEEDS_INPUT_TICKER_BOOT_KEY] = true

  // DIA-189b A2b: fire the boot retro pass without blocking instantiation.
  // The factory returns the hooks synchronously; the pass completes in
  // microtasks after the awaited list/update calls resolve.
  // DIA-260821-5r03 guard 2: run the title-suffix retro pass at most once per
  // process. On an in-process reload the pass is skipped (titles are already
  // suffixed from the first run); a full process restart clears globalThis so
  // it re-runs.
  if (!titleBootStore[NEEDS_INPUT_TITLE_BOOT_KEY]) {
    void bootRetroPass()
    titleBootStore[NEEDS_INPUT_TITLE_BOOT_KEY] = true
  }

  const hooks: Hooks = {
    // Belt-and-suspenders ENTER trigger: the wait_for_user tool path is
    // unverified upstream (per DIA-122 gate research). Dedup in enter() makes
    // a double-entry with the question.asked event harmless.
    "tool.execute.before": async (input, output) => {
      if (input.tool !== "wait_for_user") return
      const args = (output.args ?? {}) as Record<string, unknown>
      const detail =
        typeof args.reason === "string" && args.reason
          ? args.reason
          : "wait_for_user"
      await enter(input.sessionID, "question", detail)
    },

    // parentSessionId derivation (same as delegation-observer): the session
    // that calls task() IS the orchestrator. Also feeds the idle-ENTER
    // delegation counter.
    "tool.execute.after": async (input) => {
      if (input.tool !== "task") return
      parentSessionId ??= input.sessionID
      delegationsSinceIdle.set(
        input.sessionID,
        (delegationsSinceIdle.get(input.sessionID) ?? 0) + 1
      )
    },

    // CLEAR on genuine user messages only. The compaction auto-continue
    // synthetic message must NOT clear (session is still waiting): the
    // experimental.compaction.autocontinue hook sets a per-session flag that
    // is consumed here, and variant markers are a second guard.
    "chat.message": async (input) => {
      const flag = compactionSuppress.get(input.sessionID)
      if (flag !== undefined) {
        compactionSuppress.delete(input.sessionID)
        if (Date.now() - flag < COMPACTION_SUPPRESS_TTL_MS) return
      }
      if (isSyntheticVariant(input.variant)) return
      clear(input.sessionID)
    },

    // Suppress the next chat.message clear: this hook fires right before the
    // synthetic auto-continue "continue" user message is added after a
    // compaction. TTL-bounded in case the message never arrives.
    "experimental.compaction.autocontinue": async (input) => {
      compactionSuppress.set(input.sessionID, Date.now())
    },

    // C1: session lifecycle + question/permission events arrive via the
    // generic `event` catch-all (they are NOT named hooks).
    event: async (input) => {
      const event = input.event as unknown as TickerEvent

      switch (event.type) {
        case "session.created": {
          const info = event.properties?.info
          if (!info?.id) return
          const role = info.parentID ? "subagent" : "orchestrator"
          sessionMeta.set(info.id, {
            parentID: info.parentID,
            role,
            title: typeof info.title === "string" ? info.title : undefined,
            agent: typeof info.agent === "string" ? info.agent : undefined,
          })

          // DIA-189 A1 + fix: unique terminal session titles. With many
          // sessions in parallel (DIA-085 worktree model) every one shows a
          // near-identical default label, so a notification cannot say WHICH
          // session needs input. Rename-if-not-suffixed: any title without a
          // " [word-pair]" suffix (e.g. "[bold-fox]") gets
          // "<title> [<word-pair>]" appended via the SDK. The 1.18.18 runtime
          // defaults sessions to "New session - <ISO>", which the old
          // "opencode " prefix check never matched, so the suffix is appended
          // regardless of starting label (default OR user-set -
          // developer-approved, survives future default-format changes). The
          // label matches what the TUI shows after rename and the suffix is
          // exactly what notify() (A2) pins to attribute notifications to this
          // session. Guards: never double-rename a title that already carries
          // a " [word-pair]" suffix; fail-soft (a cosmetic rename must never
          // on error and continue, mirroring the plugin's fail-soft
          // pattern). The await is non-blocking; the hook is async-capable.
          const createdTitle = typeof info.title === "string" ? info.title : ""
          // DIA-189 fix: the dedupe guard is the only gate (same rationale
          // as renameDefaultTitle) - any unsuffixed title is renamed.
          const alreadySuffixed = /^\[[a-z]+-[a-z]+\]/.test(createdTitle)
          if (!alreadySuffixed) {
            const DEFAULT_SESSION_RE = /^New session - \d{4}-\d{2}-\d{2}T/
            const baseTitle =
              createdTitle !== "" && !DEFAULT_SESSION_RE.test(createdTitle)
                ? createdTitle
                : `opencode ${basename(ctx.directory)}`
            const derivedTitle = `[${sessionWordPair(info.id)}] ${baseTitle}`
            try {
              const res = await ctx.client.session.update({
                path: { id: info.id },
                body: { title: derivedTitle },
              })
              if (res.error) {
                console.warn(
                  `[needs-input-observer] session.update rename returned an error for ${info.id}: ${errorMessage(res.error)}`
                )
              }
            } catch (err) {
              console.warn(
                `[needs-input-observer] session.update rename failed for ${info.id}: ${errorMessage(err)}`
              )
            }
          }
          return
        }

        case "session.updated": {
          const sessionID = event.properties?.sessionID
          const info = event.properties?.info
          if (!sessionID || !info) return
          const meta = sessionMeta.get(sessionID)
          if (meta) {
            if (typeof info.title === "string" && info.title !== meta.title) {
              meta.title = info.title
            }
            if (typeof info.agent === "string" && info.agent !== meta.agent) {
              meta.agent = info.agent
            }
          }
          // Keep a waiting entry's title fresh so notifications and the
          // ticker view show the current label.
          const entry = waiting.get(sessionID)
          if (entry && typeof info.title === "string" && info.title !== entry.title) {
            entry.title = info.title
            persist()
          }
          return
        }

        // DIA-189b A1b + fix: the visible terminal strip is the PTY strip
        // (Pty.title), not Session.title - a pty.created/pty.updated with an
        // unsuffixed title gets the same rename-if-not-suffixed label so the
        // terminal list shows distinguishable labels and notifications (A2)
        // match the strip. Same guards and fail-soft as the session rename.
        case "pty.created":
        case "pty.updated": {
          const info = event.properties?.info
          if (!info?.id) return
          await renameDefaultTitle(info.id, info.title, "pty")
          return
        }

        case "question.asked":
        case "question.v2.asked": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          const q = event.properties?.questions?.[0]
          const detail =
            (q?.question ?? q?.text ?? "").trim() ||
            JSON.stringify(q ?? {})
          await enter(sessionID, "question", detail)
          return
        }

        case "permission.asked":
        case "permission.v2.asked": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          const p = event.properties
          const detail =
            p?.permission && Array.isArray(p.patterns) && p.patterns.length > 0
              ? `${p.permission} ${p.patterns.join(", ")}`
              : p?.action && Array.isArray(p.resources) && p.resources.length > 0
                ? `${p.action} ${p.resources.join(", ")}`
                : (p?.permission ?? p?.action ?? "permission requested")
          await enter(sessionID, "permission", detail)
          // DIA-098 R3 watchdog: record + registry row + 5-min timer. The
          // permission id lives in properties.id for BOTH v1 (PermissionAsked)
          // and v2 (PermissionV2Asked) events. The audit row is ALWAYS
          // written (ai-auditor finding 3): when the id is absent,
          // permission_id is omitted per the registry's optional-field
          // convention (conditional spread — see existing rows) and a note
          // marks the ask as unidentifiable. The watchdog timer is only
          // armed with a real id — auto-rejecting an unidentifiable
          // permission could reject the WRONG request.
          const permissionID = p?.id
          appendRegistryRow({
            event: "permission_asked_logged",
            session_id: sessionID,
            ...(typeof permissionID === "string" && permissionID
              ? { permission_id: permissionID }
              : { note: "permission_id absent - watchdog timer not armed" }),
            timestamp: new Date().toISOString(),
          })
          if (typeof permissionID === "string" && permissionID) {
            startPermissionWatch(
              sessionID,
              permissionID,
              Array.isArray(p?.patterns) ? p?.patterns : undefined
            )
          }
          return
        }

        case "session.idle": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          // Only the ORCHESTRATOR's own idle after delegations means "work
          // finished, awaiting developer direction". Subagent idle must NOT
          // enter the developer-input bucket (they return to the parent).
          const meta = sessionMeta.get(sessionID)
          const role =
            sessionID === parentSessionId
              ? "orchestrator"
              : (meta?.role ?? "unknown")
          if (role === "subagent") return
          const pending = delegationsSinceIdle.get(sessionID) ?? 0
          if (pending <= 0) return
          delegationsSinceIdle.set(sessionID, 0)
          await enter(
            sessionID,
            "idle",
            "delegations complete, awaiting developer direction"
          )
          return
        }

        case "question.replied":
        case "question.v2.replied":
        case "question.rejected":
        case "question.v2.rejected":
        case "permission.replied":
        case "permission.v2.replied": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          // DIA-098 R3: the reply references the asked permission's id —
          // v1 permission.replied carries permissionID, v2 permission.v2
          // .replied carries requestID (== the asked event's properties.id).
          // Clear the watchdog timer + ticker record for that pair.
          const repliedPermissionID =
            event.properties?.permissionID ?? event.properties?.requestID
          if (typeof repliedPermissionID === "string" && repliedPermissionID) {
            clearPermissionWatch(sessionID, repliedPermissionID)
          }
          clear(sessionID)
          return
        }

        case "session.status": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          // Agent resumed work -> clear. The runtime status is
          // {type: "idle"|"retry"|"busy"} but older shapes may emit a plain
          // string; treat any non-idle status as resumed.
          const st = event.properties?.status
          const statusType =
            typeof st === "string"
              ? st
              : typeof st === "object" && st !== null
                ? (st as { type?: string }).type
                : undefined
          if (statusType && statusType !== "idle") clear(sessionID)
          return
        }

        case "session.error": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          recordError(sessionID, errorMessage(event.properties?.error) ?? "unknown error")
          return
        }

        case "session.deleted": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          const hadWaiting = waiting.delete(sessionID)
          const hadError = errors.delete(sessionID)
          // DIA-098 R3: a deleted session cannot answer its pending
          // permissions — drop every watchdog record + timer for it (a stale
          // timer would otherwise reject against a 404 session;
          // clearPermissionWatch persists on each removal).
          clearSessionPermissionWatches(sessionID)
          sessionMeta.delete(sessionID)
          delegationsSinceIdle.delete(sessionID)
          compactionSuppress.delete(sessionID)
          if (hadWaiting || hadError) persist()
          return
        }

        default:
          return
      }
    },

    // C2: compaction survival - inject a markdown snapshot of the waiting
    // sessions into the compaction context (mirror delegation-observer C2).
    "experimental.session.compacting": async (_input, output) => {
      if (waiting.size === 0 && errors.size === 0) return
      const lines = [...waiting.values()]
        .sort((a, b) => a.since.localeCompare(b.since))
        .map(
          (e) =>
            `- session=${e.session_id} reason=${e.reason} since=${e.since} title=${e.title ?? "?"} detail=${e.detail.slice(0, 120)}`
        )
      const snapshot =
        "## Needs-Input Ticker (ticker.json snapshot)\n" +
        (lines.length > 0
          ? lines.join("\n")
          : "- no sessions waiting for developer input") +
        (errors.size > 0
          ? `\nErrors: ${errors.size} session(s) in the error bucket - see ticker.json`
          : "")
      output.context.push(snapshot)
    },

    // DIA-098 R3: hooks cleanup — stop every pending permission watchdog
    // timer on plugin unload so no orphaned auto-reject fires afterwards.
    dispose: async () => {
      for (const timer of pendingPermissionTimers.values()) {
        clearTimeout(timer)
      }
      pendingPermissionTimers.clear()
      // DIA-260821-5r03: clear all globalThis-backed singleton state so a
      // later reload starts clean (mirrors delegation-observer dispose).
      permTimersStore[NEEDS_INPUT_PERM_TIMERS_KEY] = undefined
      notifiedAsks.clear()
      notifiedAsksStore[NEEDS_INPUT_TOAST_KEY] = undefined
      titleBootStore[NEEDS_INPUT_TITLE_BOOT_KEY] = undefined
      tickerBootStore[NEEDS_INPUT_TICKER_BOOT_KEY] = undefined
    },
  }

  return hooks
}

export default needsInputObserver
