/**
 * needs-input-observer - OpenCode plugin (DIA-122): multi-session
 * "needs developer input" ticker + notifications.
 *
 * Maintains .opencode/session/ticker.json - a persistent cross-session state
 * of which opencode sessions are waiting for developer input (question asked,
 * permission asked, orchestrator idle after delegations). Many sessions run in
 * parallel (DIA-085 worktree model), so the ticker names the WAITING SESSION
 * in every notification. ticker.md is a DERIVED VIEW regenerated by
 * scripts/ticker-render.sh - never edited directly.
 *
 * State machine:
 *   ENTER  question.asked / question.v2.asked -> "question"
 *          permission.asked / permission.v2.asked -> "permission"
 *          orchestrator session.idle with delegationsSinceIdle > 0 -> "idle"
 *          (subagent idle NEVER enters)
 *          tool.execute.before wait_for_user -> "question" (belt-and-
 *          suspenders; dedup makes double-entry harmless)
 *   CLEAR  question.replied / question.v2.replied / question.rejected /
 *          question.v2.rejected / permission.replied / permission.v2.replied
 *          chat.message (genuine user messages only - synthetic compaction
 *          auto-continue messages are suppressed via a per-session flag set
 *          by the experimental.compaction.autocontinue hook, with a TTL)
 *          session.status non-idle (agent resumed work)
 *          session.deleted / session.error (error also records the bucket)
 *   ERROR  session.error -> separate "errors" bucket (NOT waiting; never
 *          notified, only listed in the ticker view)
 *
 * Notification channels (DIA-122 Phase-2 disposition, gate research
 * 2026-08-12: freedesktop dbus REQUIRES a daemon, absent on this WSL2 host):
 *   primary  in-TUI toast via ctx.client.tui.showToast()
 *   desktop  powershell.exe WinRT ToastText02 (WSL interop, zero installs)
 * Only on ENTER transitions, globally debounced ~2s. Errors stay silent in
 * notifications.
 *
 * Cross-cutting (mirror delegation-observer.ts):
 *   - fail-soft everywhere: never crash the plugin, never block the event
 *     loop; console.warn (stderr) on failure and continue.
 *   - TUI-safe logging via ctx.client.app.log(); NO raw console.* stdout
 *     writes (res007 - stdout interleaves with the TUI render surface).
 *   - subprocess stdio discarded (["ignore","ignore","ignore"]) so the WinRT
 *     toast can never corrupt the TUI.
 *   - ASCII-only source (DIA-079): no em-dashes / smart quotes anywhere,
 *     including the PowerShell one-liner.
 */
import { spawn } from "node:child_process"
import {
  closeSync,
  existsSync,
  fsyncSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from "node:fs"
import { join } from "node:path"
import type { Hooks, Plugin } from "@opencode-ai/plugin"

type WaitingReason = "question" | "permission" | "idle"

interface WaitingEntry {
  session_id: string
  title?: string
  agent?: string
  reason: WaitingReason
  detail: string
  since: string
}

interface TickerErrorEntry {
  session_id: string
  title?: string
  since: string
  error: string
}

interface TickerDoc {
  version: number
  updated_at: string
  waiting: WaitingEntry[]
  errors: TickerErrorEntry[]
}

/**
 * Custom event union for the `event` catch-all hook. The installed
 * @opencode-ai/plugin@1.18.10 v1 TS Event types do NOT declare the
 * question/permission events (and their v2 variants), but the runtime emits
 * them anyway - so we cast via `as` (same approach as the delegation-observer
 * for session lifecycle events).
 */
interface TickerEvent {
  type: string
  properties?: {
    sessionID?: string
    id?: string
    info?: { id?: string; parentID?: string; title?: string; agent?: string }
    questions?: Array<{ question?: string; text?: string; header?: string }>
    permission?: string
    patterns?: string[]
    action?: string
    resources?: string[]
    error?: unknown
    status?: unknown
  }
}

/** Best-effort extraction of a human-readable message from an error value. */
function errorMessage(err: unknown): string | undefined {
  if (err === undefined || err === null) return undefined
  if (typeof err === "string") return err
  if (
    typeof err === "object" &&
    "message" in err &&
    typeof (err as { message?: unknown }).message === "string"
  ) {
    return (err as { message: string }).message
  }
  return String(err)
}

/**
 * Synthetic-message guard for the chat.message CLEAR trigger. Compaction
 * auto-continue turns are synthetic user messages that must NOT clear a
 * waiting entry (the session is still waiting - the "continue" is machine-
 * generated). Genuine user messages clear. Variant markers are version-
 * dependent, so match conservatively.
 */
function isSyntheticVariant(variant: string | undefined): boolean {
  if (!variant) return false
  return /synthetic|auto.?continue|compaction/i.test(variant)
}

const NOTIFY_DEBOUNCE_MS = 2000
const DESKTOP_TOAST_DEBOUNCE_MS = 2000
const COMPACTION_SUPPRESS_TTL_MS = 30000

const needsInputObserver: Plugin = async (ctx) => {
  const tickerDir = join(ctx.directory, ".opencode/session")
  const tickerPath = join(tickerDir, "ticker.json")
  const tickerTmpPath = join(tickerDir, ".ticker.json.tmp")

  // sessionID -> lifecycle metadata captured at session.created. Used to
  // distinguish the orchestrator's own session (root, no parentID) from child
  // subagent sessions (role detection for the idle ENTER rule) and to carry
  // human-readable titles/agent names into waiting entries.
  const sessionMeta = new Map<
    string,
    { parentID?: string; role: "orchestrator" | "subagent"; title?: string; agent?: string }
  >()

  // Orchestrator session id, derived at runtime: the session that calls task()
  // IS the orchestrator (same derivation as delegation-observer).
  let parentSessionId: string | undefined

  // Orchestrator session -> number of task() delegations since the last
  // needs-input idle ENTER (mirror of delegation-observer's
  // delegationsSinceHandoff; reset on ENTER so repeated idles without new
  // delegations stay silent).
  const delegationsSinceIdle = new Map<string, number>()

  // sessionID -> timestamp of the last compaction auto-continue. The
  // experimental.compaction.autocontinue hook fires right before a synthetic
  // "continue" user message is added; the following chat.message must not
  // clear the waiting state. TTL-bounded so a never-consumed flag cannot
  // suppress a real user-message clear later.
  const compactionSuppress = new Map<string, number>()

  // In-memory state, seeded from ticker.json on boot (restart/compaction
  // survival). Persisted atomically on every transition.
  const waiting = new Map<string, WaitingEntry>()
  const errors = new Map<string, TickerErrorEntry>()

  // Notification debounce fences (wall-clock, monotonic enough for a ~2s
  // debounce; Date.now() matches delegation-observer conventions).
  let notifyDebounceUntil = 0
  let lastDesktopToastAt = 0

  /**
   * Generalized atomic JSON write: temp file -> fsync -> atomic rename ->
   * fsync directory (copied from delegation-observer's atomicWriteHandoff).
   * On same-filesystem rename is atomic by POSIX guarantee - a reader sees
   * either the old file or the new file, never a partial write.
   */
  function atomicWriteTicker(content: TickerDoc): void {
    const json = JSON.stringify(content, null, 2) + "\n"
    try {
      writeFileSync(tickerTmpPath, json)
      const tmpFd = openSync(tickerTmpPath, "r+")
      fsyncSync(tmpFd)
      closeSync(tmpFd)
      renameSync(tickerTmpPath, tickerPath)
      const dirFd = openSync(tickerDir, "r")
      fsyncSync(dirFd)
      closeSync(dirFd)
    } catch (err) {
      // Best-effort cleanup: unlink tmp if it still exists (rename failed).
      try {
        if (existsSync(tickerTmpPath)) unlinkSync(tickerTmpPath)
      } catch {
        // Secondary failure - nothing more we can do.
      }
      throw err
    }
  }

  /**
   * Persist the full ticker state. Fail-soft: never crash the plugin - on
   * write error console.warn (stderr only) and continue. A stale ticker is
   * recoverable; a crashed orchestrator is not.
   */
  function persist(): void {
    try {
      mkdirSync(tickerDir, { recursive: true })
      const doc: TickerDoc = {
        version: 1,
        updated_at: new Date().toISOString(),
        waiting: [...waiting.values()].sort((a, b) =>
          a.since.localeCompare(b.since)
        ),
        errors: [...errors.values()].sort((a, b) =>
          a.since.localeCompare(b.since)
        ),
      }
      atomicWriteTicker(doc)
    } catch (err) {
      console.warn(
        `[needs-input-observer] ticker.json write failed: ${errorMessage(err)}`
      )
    }
  }

  /**
   * Boot seed: re-read ticker.json so the ticker survives plugin restarts and
   * context compaction. Fail-soft on malformed JSON - start empty.
   */
  function seedFromDisk(): void {
    try {
      if (!existsSync(tickerPath)) return
      const raw = readFileSync(tickerPath, "utf-8")
      const doc = JSON.parse(raw) as Partial<TickerDoc>
      for (const e of Array.isArray(doc.waiting) ? doc.waiting : []) {
        if (e && typeof e.session_id === "string" && typeof e.reason === "string") {
          waiting.set(e.session_id, {
            session_id: e.session_id,
            title: typeof e.title === "string" ? e.title : undefined,
            agent: typeof e.agent === "string" ? e.agent : undefined,
            reason: e.reason as WaitingReason,
            detail: typeof e.detail === "string" ? e.detail : "",
            since: typeof e.since === "string" ? e.since : new Date().toISOString(),
          })
        }
      }
      for (const e of Array.isArray(doc.errors) ? doc.errors : []) {
        if (e && typeof e.session_id === "string") {
          errors.set(e.session_id, {
            session_id: e.session_id,
            title: typeof e.title === "string" ? e.title : undefined,
            since: typeof e.since === "string" ? e.since : new Date().toISOString(),
            error: typeof e.error === "string" ? e.error : "",
          })
        }
      }
    } catch (err) {
      console.warn(
        `[needs-input-observer] ticker.json boot seed failed, starting empty: ${errorMessage(err)}`
      )
    }
  }

  /** CLEAR transition: remove the session from waiting. No-op when absent. */
  function clear(sessionID: string): void {
    if (!waiting.delete(sessionID)) return
    persist()
  }

  /**
   * ERROR bucket transition (separate from waiting, per spec): record the
   * error; also drop the session from waiting (an errored turn is no longer
   * waiting for input). Errors are NEVER notified - only listed in the ticker
   * view.
   */
  function recordError(sessionID: string, error: string): void {
    waiting.delete(sessionID)
    errors.set(sessionID, {
      session_id: sessionID,
      title: sessionMeta.get(sessionID)?.title,
      since: new Date().toISOString(),
      error,
    })
    persist()
  }

  /**
   * Title fallback for notifications: cached title -> sessionMeta title ->
   * ctx.client.session.get() (fail-soft) -> id. The SDK call is awaited by
   * the caller (notify), so this path never blocks a hook on failure.
   */
  async function resolveTitle(sessionID: string): Promise<string> {
    const cached = sessionMeta.get(sessionID)?.title
    if (cached) return cached
    try {
      const res = await ctx.client.session.get({ path: { id: sessionID } })
      if (!res.error && res.data) {
        const info = res.data as { title?: string }
        if (typeof info.title === "string" && info.title) return info.title
      }
    } catch (err) {
      console.warn(
        `[needs-input-observer] session.get title fallback failed: ${errorMessage(err)}`
      )
    }
    return sessionID
  }

  /**
   * Desktop notification via powershell.exe WinRT toast (WSL interop; the
   * WSLg dbus path was gated out because freedesktop Notifications requires a
   * daemon absent on this host - DIA-122 gate research). One line, ASCII-only
   * text, single quotes doubled for PowerShell, control chars stripped.
   * STDOUT/STDERR discarded (res007 TUI corruption rule).
   */
  function fireDesktopToast(title: string, body: string): void {
    const now = Date.now()
    if (now - lastDesktopToastAt < DESKTOP_TOAST_DEBOUNCE_MS) return
    lastDesktopToastAt = now
    const ascii = (s: string): string =>
      s
        .replace(/[\r\n\t]+/g, " ")
        .replace(/[^\x20-\x7E]/g, " ")
        .replace(/'/g, "''")
        .slice(0, 180)
    const script =
      "[Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null; " +
      "$t=[Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText02); " +
      `$t.GetElementsByTagName('text').Item(0).AppendChild($t.CreateTextNode('${ascii(title)}'))|Out-Null; ` +
      `$t.GetElementsByTagName('text').Item(1).AppendChild($t.CreateTextNode('${ascii(body)}'))|Out-Null; ` +
      "[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('opencode').Show([Windows.UI.Notifications.ToastNotification]::new($t))"
    try {
      const child = spawn("powershell.exe", ["-NoProfile", "-Command", script], {
        stdio: ["ignore", "ignore", "ignore"],
      })
      // Never let a late spawn error (ENOENT, exec failure) become an
      // unhandled 'error' event - the plugin must not crash the session.
      child.on("error", (err) => {
        console.warn(
          `[needs-input-observer] powershell.exe toast spawn failed: ${errorMessage(err)}`
        )
      })
    } catch (err) {
      console.warn(
        `[needs-input-observer] powershell.exe toast failed: ${errorMessage(err)}`
      )
    }
  }

  /**
   * Notify on ENTER transitions only (~2s global debounce): in-TUI toast via
   * ctx.client.tui.showToast() (primary channel) + powershell.exe WinRT
   * desktop toast (away-from-terminal channel) + TUI-safe app.log. Fail-soft:
   * if the server client has no tui endpoint the call resolves with an error
   * (ThrowOnError=false) - we just warn and continue.
   */
  async function notify(entry: WaitingEntry): Promise<void> {
    // Every ENTER transition is logged (durable audit trail, TUI-safe). Only
    // the user-facing channels (TUI toast + desktop toast) are debounced.
    ctx.client.app.log({
      body: {
        service: "needs-input-observer",
        level: "info",
        message: `[needs-input-observer] needs-input: ${entry.reason} session=${entry.session_id} title=${entry.title ?? ""}`,
      },
    })

    const now = Date.now()
    if (now < notifyDebounceUntil) return
    notifyDebounceUntil = now + NOTIFY_DEBOUNCE_MS

    const title = entry.title || (await resolveTitle(entry.session_id)) || "Agent needs input"
    const message = `${entry.reason}: ${entry.detail}`.slice(0, 200)

    try {
      await ctx.client.tui.showToast({
        body: { title, message, variant: "warning", duration: 6000 },
      })
    } catch (err) {
      console.warn(
        `[needs-input-observer] tui.showToast failed: ${errorMessage(err)}`
      )
    }

    fireDesktopToast(title, message)
  }

  /**
   * ENTER transition: mark the session needs-input (deduped - an already-
   * waiting session is left untouched; the belt-and-suspenders wait_for_user
   * path therefore cannot double-enter), then persist + notify. The idle
   * caller resets its per-session delegation counter after entering.
   */
  async function enter(
    sessionID: string,
    reason: WaitingReason,
    detail: string
  ): Promise<void> {
    if (waiting.has(sessionID)) return
    const meta = sessionMeta.get(sessionID)
    const entry: WaitingEntry = {
      session_id: sessionID,
      title: meta?.title,
      agent: meta?.agent,
      reason,
      detail,
      since: new Date().toISOString(),
    }
    waiting.set(sessionID, entry)
    persist()
    await notify(entry)
  }

  seedFromDisk()

  const hooks: Hooks = {
    // Belt-and-suspenders ENTER trigger: the wait_for_user tool path is
    // unverified upstream (per DIA-122 gate research). Dedup in enter() makes
    // a double-entry with the question.asked event harmless.
    "tool.execute.before": async (input, output) => {
      if (input.tool !== "wait_for_user") return
      const args = (output.args ?? {}) as Record<string, unknown>
      const detail =
        typeof args.reason === "string" && args.reason
          ? args.reason
          : "wait_for_user"
      await enter(input.sessionID, "question", detail)
    },

    // parentSessionId derivation (same as delegation-observer): the session
    // that calls task() IS the orchestrator. Also feeds the idle-ENTER
    // delegation counter.
    "tool.execute.after": async (input) => {
      if (input.tool !== "task") return
      parentSessionId ??= input.sessionID
      delegationsSinceIdle.set(
        input.sessionID,
        (delegationsSinceIdle.get(input.sessionID) ?? 0) + 1
      )
    },

    // CLEAR on genuine user messages only. The compaction auto-continue
    // synthetic message must NOT clear (session is still waiting): the
    // experimental.compaction.autocontinue hook sets a per-session flag that
    // is consumed here, and variant markers are a second guard.
    "chat.message": async (input) => {
      const flag = compactionSuppress.get(input.sessionID)
      if (flag !== undefined) {
        compactionSuppress.delete(input.sessionID)
        if (Date.now() - flag < COMPACTION_SUPPRESS_TTL_MS) return
      }
      if (isSyntheticVariant(input.variant)) return
      clear(input.sessionID)
    },

    // Suppress the next chat.message clear: this hook fires right before the
    // synthetic auto-continue "continue" user message is added after a
    // compaction. TTL-bounded in case the message never arrives.
    "experimental.compaction.autocontinue": async (input) => {
      compactionSuppress.set(input.sessionID, Date.now())
    },

    // C1: session lifecycle + question/permission events arrive via the
    // generic `event` catch-all (they are NOT named hooks).
    event: async (input) => {
      const event = input.event as unknown as TickerEvent

      switch (event.type) {
        case "session.created": {
          const info = event.properties?.info
          if (!info?.id) return
          const role = info.parentID ? "subagent" : "orchestrator"
          sessionMeta.set(info.id, {
            parentID: info.parentID,
            role,
            title: typeof info.title === "string" ? info.title : undefined,
            agent: typeof info.agent === "string" ? info.agent : undefined,
          })
          return
        }

        case "session.updated": {
          const sessionID = event.properties?.sessionID
          const info = event.properties?.info
          if (!sessionID || !info) return
          const meta = sessionMeta.get(sessionID)
          if (meta) {
            if (typeof info.title === "string" && info.title !== meta.title) {
              meta.title = info.title
            }
            if (typeof info.agent === "string" && info.agent !== meta.agent) {
              meta.agent = info.agent
            }
          }
          // Keep a waiting entry's title fresh so notifications and the
          // ticker view show the current label.
          const entry = waiting.get(sessionID)
          if (entry && typeof info.title === "string" && info.title !== entry.title) {
            entry.title = info.title
            persist()
          }
          return
        }

        case "question.asked":
        case "question.v2.asked": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          const q = event.properties?.questions?.[0]
          const detail =
            (q?.question ?? q?.text ?? "").trim() ||
            JSON.stringify(q ?? {})
          await enter(sessionID, "question", detail)
          return
        }

        case "permission.asked":
        case "permission.v2.asked": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          const p = event.properties
          const detail =
            p?.permission && Array.isArray(p.patterns) && p.patterns.length > 0
              ? `${p.permission} ${p.patterns.join(", ")}`
              : p?.action && Array.isArray(p.resources) && p.resources.length > 0
                ? `${p.action} ${p.resources.join(", ")}`
                : (p?.permission ?? p?.action ?? "permission requested")
          await enter(sessionID, "permission", detail)
          return
        }

        case "session.idle": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          // Only the ORCHESTRATOR's own idle after delegations means "work
          // finished, awaiting developer direction". Subagent idle must NOT
          // enter the developer-input bucket (they return to the parent).
          const meta = sessionMeta.get(sessionID)
          const role =
            sessionID === parentSessionId
              ? "orchestrator"
              : (meta?.role ?? "unknown")
          if (role === "subagent") return
          const pending = delegationsSinceIdle.get(sessionID) ?? 0
          if (pending <= 0) return
          delegationsSinceIdle.set(sessionID, 0)
          await enter(
            sessionID,
            "idle",
            "delegations complete, awaiting developer direction"
          )
          return
        }

        case "question.replied":
        case "question.v2.replied":
        case "question.rejected":
        case "question.v2.rejected":
        case "permission.replied":
        case "permission.v2.replied": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          clear(sessionID)
          return
        }

        case "session.status": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          // Agent resumed work -> clear. The runtime status is
          // {type: "idle"|"retry"|"busy"} but older shapes may emit a plain
          // string; treat any non-idle status as resumed.
          const st = event.properties?.status
          const statusType =
            typeof st === "string"
              ? st
              : typeof st === "object" && st !== null
                ? (st as { type?: string }).type
                : undefined
          if (statusType && statusType !== "idle") clear(sessionID)
          return
        }

        case "session.error": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          recordError(sessionID, errorMessage(event.properties?.error) ?? "unknown error")
          return
        }

        case "session.deleted": {
          const sessionID = event.properties?.sessionID
          if (!sessionID) return
          const hadWaiting = waiting.delete(sessionID)
          const hadError = errors.delete(sessionID)
          sessionMeta.delete(sessionID)
          delegationsSinceIdle.delete(sessionID)
          compactionSuppress.delete(sessionID)
          if (hadWaiting || hadError) persist()
          return
        }

        default:
          return
      }
    },

    // C2: compaction survival - inject a markdown snapshot of the waiting
    // sessions into the compaction context (mirror delegation-observer C2).
    "experimental.session.compacting": async (_input, output) => {
      if (waiting.size === 0 && errors.size === 0) return
      const lines = [...waiting.values()]
        .sort((a, b) => a.since.localeCompare(b.since))
        .map(
          (e) =>
            `- session=${e.session_id} reason=${e.reason} since=${e.since} title=${e.title ?? "?"} detail=${e.detail.slice(0, 120)}`
        )
      const snapshot =
        "## Needs-Input Ticker (ticker.json snapshot)\n" +
        (lines.length > 0
          ? lines.join("\n")
          : "- no sessions waiting for developer input") +
        (errors.size > 0
          ? `\nErrors: ${errors.size} session(s) in the error bucket - see ticker.json`
          : "")
      output.context.push(snapshot)
    },
  }

  return hooks
}

export default needsInputObserver
