#!/usr/bin/env bats
# Unit tests for scripts/ticker-render.sh (DIA-122 derived-view renderer).
#
# Why these tests exist: the needs-input-observer plugin maintains
# .opencode/session/ticker.json (silent plugin write); ticker.md is a DERIVED
# VIEW regenerated by ticker-render.sh. The renderer decides WHICH sessions
# await developer input - the core ask of DIA-122 - so its output contract
# (oldest-first table, error bucket, empty state) is pinned here.
#
# Hermetic pattern (mirrors session-log.bats / check-host-jq.bats): the REAL
# script runs against TICKER_FILE / TICKER_OUTPUT env overrides pointing into
# $BATS_TEST_TMPDIR - the real .opencode/session/ticker.json and ticker.md are
# NEVER touched. jq is not faked: check-host-jq is a `make test-shell`
# prerequisite, so a functional jq is guaranteed on PATH when this suite runs.
#
# Cases:
#   T1  two waiting + one error -> waiting table oldest-first + Errors section
#   T2  missing ticker.json -> exit 0 + "no sessions waiting" state
#   T3  malformed ticker.json -> exit 0 + empty state (input tolerated)
#   T4  errors-only ticker -> empty waiting state + Errors section still shown
#   T5  pipe char in detail escaped for markdown table safety
#   T6  output written atomically at TICKER_OUTPUT

load test-helper

REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../.." && pwd)"
RENDERER="$REPO_ROOT/scripts/ticker-render.sh"

# write_ticker <name>: writes the named fixture ticker.json into
# $BATS_TEST_TMPDIR and echoes its path.
write_ticker() {
  local name="$1"
  local path="$BATS_TEST_TMPDIR/ticker-${name}.json"
  case "$name" in
    two-waiting-one-error)
      # Fixture order is NOT oldest-first on purpose (ses_003 before ses_001)
      # so the sort-by-since behavior is actually exercised.
      cat > "$path" <<'JSON'
{
  "version": 1,
  "updated_at": "2026-08-12T12:00:00Z",
  "waiting": [
    {"session_id":"ses_003","title":"Third session","agent":"coder","reason":"permission","detail":"bash /tmp/x.sh, /tmp/y.sh","since":"2026-08-12T12:00:00Z"},
    {"session_id":"ses_001","title":"First session","agent":"coder","reason":"question","detail":"What color?","since":"2026-08-12T11:00:00Z"}
  ],
  "errors": [
    {"session_id":"ses_bad","title":"Broken session","since":"2026-08-12T11:30:00Z","error":"Boom"}
  ]
}
JSON
      ;;
    pipe-detail)
      cat > "$path" <<'JSON'
{
  "version": 1,
  "updated_at": "2026-08-12T12:00:00Z",
  "waiting": [
    {"session_id":"ses_001","title":"Pipe session","agent":"coder","reason":"question","detail":"Why? A|B","since":"2026-08-12T11:00:00Z"}
  ],
  "errors": []
}
JSON
      ;;
    errors-only)
      cat > "$path" <<'JSON'
{
  "version": 1,
  "updated_at": "2026-08-12T12:00:00Z",
  "waiting": [],
  "errors": [
    {"session_id":"ses_bad","title":"Broken session","since":"2026-08-12T11:30:00Z","error":"Boom"}
  ]
}
JSON
      ;;
    malformed)
      printf 'this is not json\n' > "$path"
      ;;
  esac
  echo "$path"
}

@test "ticker-render: renders waiting table oldest-first plus error bucket" {
  local in out n1 n2
  in="$(write_ticker two-waiting-one-error)"
  out="$BATS_TEST_TMPDIR/ticker.md"

  run env TICKER_FILE="$in" TICKER_OUTPUT="$out" bash "$RENDERER"

  assert_status 0
  assert_file_exists "$out"
  assert_file_contains "$out" "# Needs-Input Ticker"
  assert_file_contains "$out" "_Generated:"
  assert_file_contains "$out" "2 session(s) waiting for developer input."
  assert_file_contains "$out" "| session_id | title | agent | reason | detail | since |"
  # Oldest first: ses_001 (since 11:00) must appear on an earlier line than
  # ses_003 (since 12:00), even though the fixture lists ses_003 first.
  n1="$(grep -nF '| ses_001 |' "$out" | head -1 | cut -d: -f1)"
  n2="$(grep -nF '| ses_003 |' "$out" | head -1 | cut -d: -f1)"
  [ -n "$n1" ] && [ -n "$n2" ] && [ "$n1" -lt "$n2" ] || {
    echo "expected ses_001 (since 11:00) before ses_003 (since 12:00); got lines $n1 / $n2" >&2
    echo "--- ticker.md ---" >&2
    cat "$out" >&2
    return 1
  }
  assert_file_contains "$out" "## Errors"
  assert_file_contains "$out" "| ses_bad | Broken session | 2026-08-12T11:30:00Z | Boom |"
}

@test "ticker-render: missing ticker.json renders empty state, exit 0" {
  local out
  out="$BATS_TEST_TMPDIR/missing.md"

  run env TICKER_FILE="$BATS_TEST_TMPDIR/does-not-exist.json" \
    TICKER_OUTPUT="$out" bash "$RENDERER"

  assert_status 0
  assert_file_exists "$out"
  assert_file_contains "$out" "# Needs-Input Ticker"
  assert_file_contains "$out" "No sessions waiting for developer input."
  assert_output_not_contains "## Errors"
}

@test "ticker-render: malformed ticker.json is tolerated, exit 0" {
  local in out
  in="$(write_ticker malformed)"
  out="$BATS_TEST_TMPDIR/malformed.md"

  run env TICKER_FILE="$in" TICKER_OUTPUT="$out" bash "$RENDERER"

  assert_status 0
  assert_file_exists "$out"
  assert_file_contains "$out" "No sessions waiting for developer input."
}

@test "ticker-render: errors-only ticker shows empty waiting state plus Errors" {
  local in out
  in="$(write_ticker errors-only)"
  out="$BATS_TEST_TMPDIR/errors-only.md"

  run env TICKER_FILE="$in" TICKER_OUTPUT="$out" bash "$RENDERER"

  assert_status 0
  assert_file_contains "$out" "No sessions waiting for developer input."
  assert_file_contains "$out" "## Errors"
  assert_file_contains "$out" "| ses_bad | Broken session | 2026-08-12T11:30:00Z | Boom |"
  assert_output_not_contains "session(s) waiting"
}

@test "ticker-render: pipe characters in cells escaped for table safety" {
  local in out
  in="$(write_ticker pipe-detail)"
  out="$BATS_TEST_TMPDIR/pipe.md"

  run env TICKER_FILE="$in" TICKER_OUTPUT="$out" bash "$RENDERER"

  assert_status 0
  assert_file_contains "$out" "Why? A&#124;B"
  assert_file_contains "$out" "| Pipe session |"
}
